export enum AppActions {
    BINARYSTRSIAFI = 'CHANGE_BINARYSTRSIAFI',
    BINARYSTREFDREINF = 'CHANGE_BINARYSTREFDREINF',
    SIAFI_FILE = 'CHANGE_SIAFI_FILE',
    EFD_FILE = 'CHANGE_EFD_FILE',
    DIFFERENT_VALUES = 'CHANGE_DIFFERENT_VALUES',
    EFD_TOTAL_VALUE = 'CHANGE_EFD_TOTAL_VALUE',
    SIAFI_TOTAL_VALUE = 'CHANGE_SIAFI_TOTAL_VALUE',
    TOTAL_VALUE_DIFFERENCE = 'CHANGE_TOTAL_VALUE_DIFFERENCE',
    CNPJ_ERRORS = 'CHANGE_CNPJ_ERRORS',
    SIAFI_VALUES_COLLECTORS = 'CHANGE_SIAFI_VALUES_COLLECTORS',
    EFD_VALUES_CNPJS = 'CHANGE_EFD_VALUES_CNPJS',
  }